##
##
## Cuidado ao modificar este arquivo manualmente !
##
'Add a todo'=>'Adicionar um afazer',
'Assignee'=>'Responsável',
'Calendar'=>'Calendário',
'Choose a Category'=>'Escolha uma categoria',
'Closed Items'=>'Itens fechados',
'GTD Active Projects'=>'Afazeres de Projetos Ativos',
'GTD All Projects'=>'Afazeres de Todos os Projetos',
'No assignees available'=>'Sem responsáveis',
'Overdue'=>'Deveria ter terminado',
'Related to which contact?'=>'Relativo a qual contato?',
'Related to which project?'=>'Relativo a qual projeto?',
'Todo Items'=>'Itens a Fazer',
'TodoList'=>'Lista de Afazeres',
'Todolist'=>'Lista de Afazeres',
'todolist'=>'Lista de Afazeres',
'TodoOwner'=>'Minha Lista de Afazeres',
'todos'=>'Afazeres',
'Todos'=>'Afazeres',
'When is it due?'=>'Até quando fazer?',